apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace-cp4waiops.yaml
  - base/openshift-marketplace-ibm-cp-catalogs-waiops.yaml
  - base/openshift-marketplace-ibm-entitlement-key.yaml
